---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/aws-ia/pre-commit-configs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: v1.6.1
    hooks:
      - id: aws-ia-meta-hook
  -
    repo: https://github.com/ansible/ansible-lint
    rev: v26.3.0
    hooks:
      - id: ansible-lint
        files: \.(yml|yaml)$
        args: ["--fix"]
        additional_dependencies:
          - ansible-core>=2.15
